export const FILTER_CHANGE: string = 'FILTER_CHANGE';
export const FILTER_CHANGED: string = 'FILTER_CHANGED';

export const BLOCK_SIZE_CHANGED: string = 'BLOCK_SIZE_CHANGED';

export const STRENGTH_CHANGED: string = 'STRENGTH_CHANGED';
export const CHANNELS_WILL_CHANGE: string = 'CHANNELS_WILL_CHANGE';
export const CHANNELS_CHANGED: string = 'CHANNELS_CHANGED';

export const FILTER_NONE = 'FILTER_NONE';
export const FILTER_MINIMUM = 'FILTER_MINIMUM';
export const FILTER_MAKSIMUM = 'FILTER_MAKSIMUM';
export const FILTER_MEDIANA = 'FILTER_MEDIANA';
export const FILTER_REVERSE = 'FILTER_REVERSE';

export const STORAGE_ORIGINAL_IMAGE = 'STORAGE_ORIGINAL_IMAGE';
export const STORAGE_FILTERED_IMAGE = 'STORAGE_FILTERED_IMAGE';
